name: hello
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pytest
    - pytest_cov
    - setuptools
    - setuptools_scm
    - wheel
    - pytest-console-scripts
    - build
